// @vitest-environment jsdom
/**
 * SpotPlayer hand-reading-spot test (ticket 0078) — proves the board-reading recognition spot renders and
 * grades end-to-end through the SHARED {@link SpotPlayer} pieces ({@link SpotView}, {@link SpotAnswers},
 * {@link ResultSheet}), exactly like a coach/calculation spot, with the same Testing Library idiom as
 * {@link SpotPlayer.calculation.test} / {@link DrillSession.test}.
 *
 * The cardinal assertion (as everywhere): the rendered result reflects the engine's `gradeSpot`, never
 * hardcoded copy. The spot is generated by the SAME pure generator the app drives, so the test re-derives
 * the correct category from the engine's `evaluate7` (`gradeSpot`) and cross-checks the DOM against it —
 * no answer key.
 */

import { useState } from 'react'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, describe, expect, it } from 'vitest'
import { generateSpot } from '@holdem/drills'
import { gradeSpot, type GradeResult, type HandReadingSpot } from '@holdem/curriculum'
import { ResultSheet, SpotAnswers, SpotView } from './SpotPlayer.js'

afterEach(cleanup)

/** A generated hand-reading spot for a fixed seed — deterministic, so the test knows its correct category. */
function handSpot(seed = 7, street: 'flop' | 'turn' | 'river' = 'flop'): HandReadingSpot {
  return generateSpot(seed, { kind: 'hand-reading', street }) as HandReadingSpot
}

/** A minimal harness wiring the shared pieces the way DrillSession does — pick, grade, show the sheet. */
function Harness({ spot }: { readonly spot: HandReadingSpot }): React.JSX.Element {
  const [chosen, setChosen] = useState<number | null>(null)
  const [result, setResult] = useState<GradeResult | null>(null)
  return (
    <>
      <SpotView spot={spot} />
      <SpotAnswers
        spot={spot}
        chosen={chosen}
        result={result}
        onPick={(i) => {
          setChosen(i)
          setResult(gradeSpot(spot, i))
        }}
      />
      {result !== null ? (
        <ResultSheet
          result={result}
          spot={spot}
          title="Drill review"
          ctaLabel="Next spot →"
          ariaLabel="Drill review"
          onAdvance={() => {}}
          onClose={() => {}}
        />
      ) : null}
    </>
  )
}

describe('SpotPlayer — hand-reading spot', () => {
  it('renders the category choices as tappable buttons and a money-less board felt', () => {
    const spot = handSpot()
    render(<Harness spot={spot} />)
    const answers = screen.getByTestId('answers')
    spot.choices.forEach((choice, i) => {
      expect(within(answers).getByTestId(`answer-${i}`).textContent).toBe(choice.label)
    })
    // The board-reading felt has NO price chip — it weighs no pot odds, it asks "what do you have?".
    expect(screen.queryByTestId('price-chip')).toBeNull()
  })

  it('grading the evaluate7-derived category is correct; the sheet shows the made hand', () => {
    const spot = handSpot()
    const correctIndex = gradeSpot(spot, 0).correctIndex
    const grade = gradeSpot(spot, correctIndex)
    expect(grade.correct).toBe(true)

    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId(`answer-${correctIndex}`))

    expect(screen.getByTestId('result-sheet')).toBeTruthy()
    expect(screen.getByTestId('result-verdict').getAttribute('data-verdict')).toBe('good')
    // The hand-reading result surfaces the correct category + the derivation, both straight from gradeSpot.
    expect(screen.getByTestId('metric-answer').textContent).toBe(spot.choices[correctIndex]!.label)
    expect(screen.getByTestId('result-why').textContent).toBe(grade.explanation)
  })

  it('grading a wrong category shows a leak (never "WRONG"), naming the made hand', () => {
    const spot = handSpot()
    const correctIndex = gradeSpot(spot, 0).correctIndex
    const wrongIndex = spot.choices.findIndex((_c, i) => i !== correctIndex)
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId(`answer-${wrongIndex}`))

    expect(screen.getByTestId('result-verdict').getAttribute('data-verdict')).toBe('leak')
    const sheet = screen.getByTestId('result-sheet')
    expect(sheet.textContent).not.toContain('WRONG')
    // The true category is named, so the miss still teaches what the cards actually were.
    expect(sheet.textContent).toContain(spot.choices[correctIndex]!.label)
  })

  it('renders a river-board hand-reading spot the same way (5-card board)', () => {
    const spot = handSpot(3, 'river')
    expect(spot.board).toHaveLength(5)
    const correctIndex = gradeSpot(spot, 0).correctIndex
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId(`answer-${correctIndex}`))
    expect(screen.getByTestId('metric-answer').textContent).toBe(spot.choices[correctIndex]!.label)
  })
})
