// @vitest-environment jsdom
/**
 * SpotPlayer calculation-spot test (ticket 0077) — proves the numeric-retrieval spot renders and grades
 * end-to-end through the SHARED {@link SpotPlayer} pieces ({@link SpotView}, {@link SpotAnswers},
 * {@link ResultSheet}), exactly like a coach/preflop spot, with the same Testing Library idiom as
 * {@link DrillSession.test}.
 *
 * The cardinal assertion (as everywhere): the rendered result reflects the engine's `gradeSpot`, never
 * hardcoded copy. The spot is generated by the SAME pure generator the app drives, so the test re-derives
 * the correct bucket from the math (`gradeSpot`) and cross-checks the DOM against it — no answer key.
 */

import { useState } from 'react'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, describe, expect, it } from 'vitest'
import { generateSpot } from '@holdem/drills'
import { gradeSpot, type CalculationSpot, type GradeResult } from '@holdem/curriculum'
import { ResultSheet, SpotAnswers, SpotView } from './SpotPlayer.js'

afterEach(cleanup)

/** A generated calculation spot for a fixed seed — deterministic, so the test knows its correct bucket. */
function calcSpot(
  seed = 7,
  quantity: 'pot-odds' | 'required-equity' | 'equity' = 'required-equity',
) {
  return generateSpot(seed, { kind: 'calculation', quantity }) as CalculationSpot
}

/** A minimal harness wiring the shared pieces the way DrillSession does — pick, grade, show the sheet. */
function Harness({ spot }: { readonly spot: CalculationSpot }): React.JSX.Element {
  const [chosen, setChosen] = useState<number | null>(null)
  const [result, setResult] = useState<GradeResult | null>(null)
  return (
    <>
      <SpotView spot={spot} />
      <SpotAnswers
        spot={spot}
        chosen={chosen}
        result={result}
        onPick={(i) => {
          setChosen(i)
          setResult(gradeSpot(spot, i))
        }}
      />
      {result !== null ? (
        <ResultSheet
          result={result}
          spot={spot}
          title="Drill review"
          ctaLabel="Next spot →"
          ariaLabel="Drill review"
          onAdvance={() => {}}
          onClose={() => {}}
        />
      ) : null}
    </>
  )
}

describe('SpotPlayer — calculation spot', () => {
  it('renders the number buckets as tappable answer buttons (the spot states the situation)', () => {
    const spot = calcSpot()
    render(<Harness spot={spot} />)
    const answers = screen.getByTestId('answers')
    // Every offered bucket renders, in order, by its label — reusing the same answer-button machinery.
    spot.choices.forEach((choice, i) => {
      expect(within(answers).getByTestId(`answer-${i}`).textContent).toBe(choice.label)
    })
    // The shared postflop felt shows the price (it carries a priced SpotContext like a coach spot).
    expect(screen.getByTestId('price-chip').textContent).toContain(String(spot.context.toCall))
  })

  it('grading the bucket the math lands in is correct; the sheet shows the derived number', () => {
    const spot = calcSpot()
    const correctIndex = gradeSpot(spot, 0).correctIndex
    const grade = gradeSpot(spot, correctIndex)
    expect(grade.correct).toBe(true)

    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId(`answer-${correctIndex}`))

    expect(screen.getByTestId('result-sheet')).toBeTruthy()
    expect(screen.getByTestId('result-verdict').getAttribute('data-verdict')).toBe('good')
    // The calculation result surfaces the correct bucket + the show-the-math derivation (not the verdict
    // metric row — there is no coach verdict). Both come straight from gradeSpot, never hardcoded.
    expect(screen.getByTestId('metric-answer').textContent).toBe(spot.choices[correctIndex]!.label)
    expect(screen.getByTestId('result-why').textContent).toBe(grade.explanation)
  })

  it('grading a wrong bucket shows a leak (never "WRONG"), naming the correct bucket', () => {
    const spot = calcSpot()
    const correctIndex = gradeSpot(spot, 0).correctIndex
    const wrongIndex = spot.choices.findIndex((_c, i) => i !== correctIndex)
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId(`answer-${wrongIndex}`))

    expect(screen.getByTestId('result-verdict').getAttribute('data-verdict')).toBe('leak')
    const sheet = screen.getByTestId('result-sheet')
    expect(sheet.textContent).not.toContain('WRONG')
    // The correct bucket label is named, so the miss still teaches.
    expect(sheet.textContent).toContain(spot.choices[correctIndex]!.label)
  })

  it('renders an equity-estimate calculation spot the same way', () => {
    const spot = calcSpot(3, 'equity')
    const correctIndex = gradeSpot(spot, 0).correctIndex
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId(`answer-${correctIndex}`))
    expect(screen.getByTestId('metric-answer').textContent).toBe(spot.choices[correctIndex]!.label)
  })
})
