// @vitest-environment jsdom
/**
 * SpotPlayer sizing-spot test (ticket 0105) — proves the "pick the bet size" spot renders and grades
 * end-to-end through the SHARED {@link SpotPlayer} pieces ({@link SpotView}, {@link SpotAnswers},
 * {@link ResultSheet}), exactly like a coach/calculation spot, with the same Testing Library idiom as
 * {@link SpotPlayer.calculation.test}.
 *
 * The cardinal assertion (as everywhere): the rendered result reflects the engine's `gradeSpot`, never
 * hardcoded copy. The spot is generated by the SAME pure generator the app drives, so the test re-derives
 * the correct (in-band) size from the coach's band grader via `gradeSpot` and cross-checks the DOM against
 * it — no answer key. The wrong-pick explanation is the coach's OWN sizing `why`, the play-parity criterion.
 */

import { useState } from 'react'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, describe, expect, it } from 'vitest'
import { generateSpot } from '@holdem/drills'
import { gradeSpot, type GradeResult, type SizingSpot } from '@holdem/curriculum'
import { ResultSheet, SpotAnswers, SpotView } from './SpotPlayer.js'

afterEach(cleanup)

/** A generated sizing spot for a fixed seed — deterministic, so the test knows its in-band size. */
function sizingSpot(seed = 7): SizingSpot {
  return generateSpot(seed, { kind: 'sizing' }) as SizingSpot
}

/** A minimal harness wiring the shared pieces the way DrillSession does — pick, grade, show the sheet. */
function Harness({ spot }: { readonly spot: SizingSpot }): React.JSX.Element {
  const [chosen, setChosen] = useState<number | null>(null)
  const [result, setResult] = useState<GradeResult | null>(null)
  return (
    <>
      <SpotView spot={spot} />
      <SpotAnswers
        spot={spot}
        chosen={chosen}
        result={result}
        onPick={(i) => {
          setChosen(i)
          setResult(gradeSpot(spot, i))
        }}
      />
      {result !== null ? (
        <ResultSheet
          result={result}
          spot={spot}
          title="Drill review"
          ctaLabel="Next spot →"
          ariaLabel="Drill review"
          onAdvance={() => {}}
          onClose={() => {}}
        />
      ) : null}
    </>
  )
}

describe('SpotPlayer — sizing spot', () => {
  it('renders the size options as tappable buttons on an unbet felt', () => {
    const spot = sizingSpot()
    render(<Harness spot={spot} />)
    const answers = screen.getByTestId('answers')
    // Every offered size renders, in order, by its peg label — reusing the same answer-button machinery.
    spot.choices.forEach((choice, i) => {
      expect(within(answers).getByTestId(`answer-${i}`).textContent).toBe(choice.label)
    })
    // The shared felt shows the pot and that the spot is UNBET (the hero is choosing a bet, not a price).
    expect(screen.getByTestId('price-chip').textContent).toContain('Unbet')
  })

  it('picking the in-band size is correct; the sheet shows the size + the coach why', () => {
    const spot = sizingSpot()
    const correctIndex = gradeSpot(spot, 0).correctIndex
    const grade = gradeSpot(spot, correctIndex)
    expect(grade.correct).toBe(true)

    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId(`answer-${correctIndex}`))

    expect(screen.getByTestId('result-sheet')).toBeTruthy()
    expect(screen.getByTestId('result-verdict').getAttribute('data-verdict')).toBe('good')
    // The sizing result surfaces the in-band size + the chosen size's `why` (no coach continue verdict).
    // Both come straight from gradeSpot, never hardcoded — the why is the coach's own sizing explanation.
    expect(screen.getByTestId('metric-answer').textContent).toBe(spot.choices[correctIndex]!.label)
    expect(screen.getByTestId('result-why').textContent).toBe(grade.explanation)
  })

  it('picking an out-of-band size shows a leak (never "WRONG"), explained with the coach\'s own why', () => {
    const spot = sizingSpot()
    const correctIndex = gradeSpot(spot, 0).correctIndex
    const wrongIndex = spot.choices.findIndex((_c, i) => i !== correctIndex)
    const grade = gradeSpot(spot, wrongIndex)
    expect(grade.correct).toBe(false)

    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId(`answer-${wrongIndex}`))

    expect(screen.getByTestId('result-verdict').getAttribute('data-verdict')).toBe('leak')
    const sheet = screen.getByTestId('result-sheet')
    expect(sheet.textContent).not.toContain('WRONG')
    // The correct (in-band) size is named, so the miss still teaches…
    expect(sheet.textContent).toContain(spot.choices[correctIndex]!.label)
    // …and the why shown IS the coach's own out-of-band sizing explanation for the chosen size (play parity).
    expect(screen.getByTestId('result-why').textContent).toBe(grade.explanation)
  })
})
