// @vitest-environment jsdom
/**
 * SpotPlayer feedback-depth + cross-link test (ticket 0079) — proves the graded {@link ResultSheet}
 * (a) deepens the feedback to SHOW THE MATH the player should have computed, distinguishing a clear
 * leak from a break-even coin-flip, and (b) cross-links the result into the EXISTING reference
 * overlays ({@link ChartOverlay} / {@link GlossaryOverlay}) — no new explanation engine, no new
 * reference UI.
 *
 * As everywhere, correctness/wording is derived from the engine + the shared `@holdem/format`
 * helpers, never hardcoded: the spot is generated by the SAME pure generator the app drives, and the
 * test re-derives the expected math line from `gradeSpot` + `priceComparison`, then cross-checks the
 * DOM against it. The cross-link assertions drive the real overlays the CoachDrawer uses.
 */

import { useState } from 'react'
import { cleanup, fireEvent, render, screen, within } from '@testing-library/react'
import { afterEach, describe, expect, it, vi } from 'vitest'
import { generateSpot } from '@holdem/drills'
import { type DecisionVerdict } from '@holdem/coach'
import { countDrawOuts, outsToEquity } from '@holdem/odds'
import {
  gradeSpot,
  OUTS_OVERSTATE_TOLERANCE,
  parseDrillSpot,
  type GradeResult,
  type Spot,
  type SpotVerdict,
} from '@holdem/curriculum'
import { priceComparison } from '@holdem/format'
import { ResultSheet, SpotAnswers, SpotView } from './SpotPlayer.js'

afterEach(cleanup)

/** Discriminate the postflop verdict (the one carrying a pot-odds price) — mirrors SpotPlayer's own guard. */
function isDecisionVerdict(verdict: SpotVerdict): verdict is DecisionVerdict {
  return 'potOddsThreshold' in verdict
}

/** A minimal harness wiring the shared pieces the way DrillSession does — pick, grade, show the sheet. */
function Harness({ spot }: { readonly spot: Spot }): React.JSX.Element {
  const [chosen, setChosen] = useState<number | null>(null)
  const [result, setResult] = useState<GradeResult | null>(null)
  return (
    <>
      <SpotView spot={spot} />
      <SpotAnswers
        spot={spot}
        chosen={chosen}
        result={result}
        onPick={(i) => {
          setChosen(i)
          setResult(gradeSpot(spot, i))
        }}
      />
      {result !== null ? (
        <ResultSheet
          result={result}
          spot={spot}
          title="Drill review"
          ctaLabel="Next spot →"
          ariaLabel="Drill review"
          onAdvance={() => {}}
          onClose={() => {}}
        />
      ) : null}
    </>
  )
}

/** A generated priced coach spot for a seed — always carries a non-zero price (a real pot-odds spot). */
function pricedSpot(seed: number): Spot {
  return generateSpot(seed, { kind: 'coach', priceMode: 'priced' })
}

/**
 * Find the first seed (in `0..200`) whose priced coach spot's verdict has the wanted EV-correct
 * decision (`'fold'` ⇒ a clear fold, `'continue'` ⇒ a clear continue) — the side the math line names,
 * independent of what the player did. Read straight off the engine, so there is no answer key.
 */
function seedForDecision(want: 'fold' | 'continue'): number | undefined {
  for (let seed = 0; seed <= 200; seed++) {
    const verdict = gradeSpot(pricedSpot(seed), 0).verdict
    if (
      verdict !== undefined &&
      isDecisionVerdict(verdict) &&
      verdict.verdict !== 'breakEven' &&
      verdict.correctDecision === want
    ) {
      return seed
    }
  }
  return undefined
}

/** Find the first seed (in `0..200`) whose priced coach spot grades to a break-even coin-flip. */
function seedForBreakEven(): number | undefined {
  for (let seed = 0; seed <= 200; seed++) {
    const verdict = gradeSpot(pricedSpot(seed), 0).verdict
    if (verdict !== undefined && isDecisionVerdict(verdict) && verdict.verdict === 'breakEven') {
      return seed
    }
  }
  return undefined
}

describe('SpotPlayer — show-the-math feedback (ticket 0079)', () => {
  it('a priced spot surfaces the had-vs-needed math line, derived from the verdict (not hardcoded)', () => {
    const spot = pricedSpot(7)
    const decision = gradeSpot(spot, 0).verdict
    expect(decision !== undefined && isDecisionVerdict(decision)).toBe(true)
    const expected = priceComparison(decision as DecisionVerdict)
    expect(expected).not.toBeNull()

    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId('answer-0'))

    const math = screen.getByTestId('result-math')
    // The line is exactly what @holdem/format builds from the verdict — same wording as the table.
    expect(math.textContent).toBe(expected)
    // It states both the equity HAD and the equity NEEDED — the comparison the player should have made.
    expect(math.textContent).toContain('equity')
    expect(math.textContent).toContain('needed')
  })

  it('a clear fold reads "short of the price, so it\'s a fold" — distinct from a coin-flip', () => {
    const seed = seedForDecision('fold')
    expect(seed).toBeDefined()
    const spot = pricedSpot(seed!)
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId('answer-0'))

    // The math line names the EV-correct side (fold), independent of what the player did.
    const math = screen.getByTestId('result-math')
    expect(math.textContent).toContain('short of the price')
    expect(math.textContent).toContain('fold')
    expect(math.textContent!.toLowerCase()).not.toContain('coin-flip')
  })

  it('a clear continue reads "clear of the price, so continuing is the play"', () => {
    const seed = seedForDecision('continue')
    expect(seed).toBeDefined()
    const spot = pricedSpot(seed!)
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId('answer-0'))

    const math = screen.getByTestId('result-math')
    expect(math.textContent).toContain('clear of the price')
    expect(math.textContent).toContain('continuing')
    expect(math.textContent!.toLowerCase()).not.toContain('coin-flip')
  })

  it('a break-even spot reads as a coin-flip (close, not a mistake) — distinct from a clear leak', () => {
    const seed = seedForBreakEven()
    expect(seed).toBeDefined()
    const spot = pricedSpot(seed!)
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId('answer-0'))

    // A break-even spot is never a leak: the math line says coin-flip, distinct from a clear fold/continue.
    const math = screen.getByTestId('result-math')
    expect(math.textContent!.toLowerCase()).toContain('coin-flip')
    expect(math.textContent!.toLowerCase()).toContain('equally fine')
  })

  it('a free check shows no math line — there is no price to compare equity against', () => {
    // An unconstrained coach spot can be a free decision (toCall === 0). Find one.
    let freeSpot: Spot | undefined
    for (let seed = 0; seed <= 200; seed++) {
      const spot = generateSpot(seed, { kind: 'coach' })
      if (spot.kind === 'coach' && spot.context.toCall === 0) {
        freeSpot = spot
        break
      }
    }
    expect(freeSpot).toBeDefined()
    render(<Harness spot={freeSpot!} />)
    fireEvent.click(screen.getByTestId('answer-0'))
    // The priced math line is absent; the shared free-card "why" line still renders.
    expect(screen.queryByTestId('result-math')).toBeNull()
    expect(screen.getByTestId('result-why')).toBeTruthy()
  })

  it('the calculation spot keeps its no-verdict show-the-math path (no priced math line)', () => {
    const spot = generateSpot(7, { kind: 'calculation', quantity: 'required-equity' })
    const correctIndex = gradeSpot(spot, 0).correctIndex
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId(`answer-${correctIndex}`))
    // It has no coach verdict, so no priced comparison line — its derivation IS the show-the-math feedback.
    expect(screen.queryByTestId('result-math')).toBeNull()
    expect(screen.getByTestId('result-calculation')).toBeTruthy()
  })
})

describe('SpotPlayer — show the work (worked steps)', () => {
  it('expands the worked steps on a miss, walking the price → equity → compare derivation', () => {
    // A priced coach spot and an answer index that grades WRONG, so the steps auto-expand on the miss.
    let found: { spot: Spot; wrongIndex: number } | undefined
    for (let seed = 0; seed <= 200 && found === undefined; seed++) {
      const spot = pricedSpot(seed)
      for (let i = 0; i < spot.choices.length; i++) {
        if (!gradeSpot(spot, i).correct) {
          found = { spot, wrongIndex: i }
          break
        }
      }
    }
    expect(found).toBeDefined()
    render(<Harness spot={found!.spot} />)
    fireEvent.click(screen.getByTestId(`answer-${found!.wrongIndex}`))

    const toggle = screen.getByTestId('worked-steps-toggle')
    expect(toggle.getAttribute('aria-expanded')).toBe('true')
    // The full derivation is visible: price → equity → compare (three steps on a priced spot).
    expect(screen.getAllByTestId('worked-step').length).toBeGreaterThanOrEqual(3)
    const text = (screen.getByTestId('worked-steps').textContent ?? '').toLowerCase()
    expect(text).toContain('price')
    expect(text).toContain('equity')
  })

  it('never presents a DOMINATED draw as a clean rule-of-N derivation (no contradictory numbers)', () => {
    // The rule of 2-and-4 counts raw odds to complete, blind to whether the made hand wins. Against a
    // heavy barreling line a draw can be dominated — ~18% raw odds yet ~1% real equity. Scan the real
    // generator: wherever the outs estimate overstates the coach's read, the equity step must REFRAME
    // ("often behind") rather than sit two contradictory numbers side by side; where they agree, it
    // shows the derivation. This locks the fix for the 18%-vs-1.4% contradiction.
    let sawDominated = false
    let sawClean = false
    for (let seed = 0; seed <= 600; seed++) {
      const spot = generateSpot(seed, { kind: 'coach', priceMode: 'priced' })
      if (spot.kind !== 'coach') continue
      const { holeCards, board } = spot.context
      if (board.length !== 3 && board.length !== 4) continue
      const draw = countDrawOuts(holeCards, board)
      if (draw === null) continue
      const res = gradeSpot(spot, 0)
      const verdict = res.verdict
      if (verdict === undefined || !isDecisionVerdict(verdict)) continue
      const approx = outsToEquity(draw.outs, board.length === 3 ? 2 : 1)
      const step = (res.workedSteps ?? []).find((s) => s.label === 'Your equity')
      expect(step).toBeDefined()
      if (approx - verdict.equity > OUTS_OVERSTATE_TOLERANCE) {
        sawDominated = true
        expect(step!.detail).toContain('often behind') // the honest reality-check
        expect(step!.detail).not.toContain('the rule of') // never the clean derivation
      } else {
        sawClean = true
        expect(step!.detail).toContain('the rule of') // the derivation is shown when it holds up
      }
    }
    // The generator yields both, so the one-directional guard is exercised both ways (not vacuous).
    expect(sawClean).toBe(true)
    expect(sawDominated).toBe(true)
  })

  it('collapses the worked steps on a correct answer, revealing them on toggle', () => {
    let found: { spot: Spot; rightIndex: number } | undefined
    for (let seed = 0; seed <= 200 && found === undefined; seed++) {
      const spot = pricedSpot(seed)
      for (let i = 0; i < spot.choices.length; i++) {
        if (gradeSpot(spot, i).correct) {
          found = { spot, rightIndex: i }
          break
        }
      }
    }
    expect(found).toBeDefined()
    render(<Harness spot={found!.spot} />)
    fireEvent.click(screen.getByTestId(`answer-${found!.rightIndex}`))

    // Collapsed by default on a correct answer — the steps are tucked behind the toggle.
    const toggle = screen.getByTestId('worked-steps-toggle')
    expect(toggle.getAttribute('aria-expanded')).toBe('false')
    expect(screen.queryAllByTestId('worked-step')).toHaveLength(0)
    // Still available to review: tapping reveals the work.
    fireEvent.click(toggle)
    expect(toggle.getAttribute('aria-expanded')).toBe('true')
    expect(screen.getAllByTestId('worked-step').length).toBeGreaterThanOrEqual(3)
  })
})

describe('SpotPlayer — copy spot for a bug report', () => {
  it('copies a reproducible spot+grade blob that re-grades identically', () => {
    const writeText = vi.fn().mockResolvedValue(undefined)
    vi.stubGlobal('navigator', { clipboard: { writeText } })

    const spot = pricedSpot(7)
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId('answer-0'))
    fireEvent.click(screen.getByTestId('copy-spot'))

    expect(writeText).toHaveBeenCalledTimes(1)
    const blob = writeText.mock.calls[0]![0] as string
    expect(blob).toContain('holdem-drill-spot-report')

    // The blob is reproducible: parse it back and re-grade → exactly what the player saw, worked steps
    // and all. This is the whole point — a bug report carries the spot, not just a screenshot.
    const original = gradeSpot(spot, 0)
    const { spot: parsed, chosenIndex } = parseDrillSpot(blob)
    expect(chosenIndex).toBe(0)
    const regraded = gradeSpot(parsed, chosenIndex)
    expect(regraded.correct).toBe(original.correct)
    expect(regraded.correctIndex).toBe(original.correctIndex)
    expect(regraded.explanation).toBe(original.explanation)
    expect(regraded.workedSteps).toEqual(original.workedSteps)

    vi.unstubAllGlobals()
  })

  it('does not throw when the clipboard API is unavailable', () => {
    vi.stubGlobal('navigator', {})
    render(<Harness spot={pricedSpot(7)} />)
    fireEvent.click(screen.getByTestId('answer-0'))
    expect(() => fireEvent.click(screen.getByTestId('copy-spot'))).not.toThrow()
    vi.unstubAllGlobals()
  })
})

describe('SpotPlayer — reference cross-links (ticket 0079)', () => {
  it('a preflop result offers "See the chart" → opens ChartOverlay spotlighting the hero hand', () => {
    const spot = generateSpot(11, { kind: 'preflop' })
    expect(spot.kind).toBe('preflop')
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId('answer-0'))

    // Closed until asked.
    expect(screen.queryByTestId('chart-modal')).toBeNull()
    fireEvent.click(screen.getByTestId('result-open-chart'))
    // The SAME ChartOverlay the CoachDrawer uses, with the hero's hand ringed (its `chart-current` cell).
    expect(screen.getByTestId('chart-modal')).toBeTruthy()
    expect(screen.getByTestId('chart-current')).toBeTruthy()
  })

  it('a non-preflop (priced coach) result has no chart link — the chart graded only preflop', () => {
    const spot = pricedSpot(7)
    render(<Harness spot={spot} />)
    fireEvent.click(screen.getByTestId('answer-0'))
    expect(screen.queryByTestId('result-open-chart')).toBeNull()
  })

  it('tapping a glossary term in a preflop grade explanation opens GlossaryOverlay on that term', () => {
    // Scan for a preflop spot whose hero-hand grade explanation carries a linkable term (e.g. a set /
    // kicker / nuts hand) — those render through GlossaryText as tappable buttons.
    let target: { spot: Spot; term: string } | undefined
    for (let seed = 0; seed <= 200 && target === undefined; seed++) {
      const spot = generateSpot(seed, { kind: 'preflop' })
      render(<Harness spot={spot} />)
      fireEvent.click(screen.getByTestId('answer-0'))
      const why = screen.queryByTestId('result-grade-why')
      const link = why?.querySelector<HTMLButtonElement>('button.glossary-link')
      if (link) {
        const term = link.getAttribute('data-testid')!.replace('glossary-link-', '')
        target = { spot, term }
      }
      cleanup()
    }
    expect(target).toBeDefined()

    render(<Harness spot={target!.spot} />)
    fireEvent.click(screen.getByTestId('answer-0'))
    const why = screen.getByTestId('result-grade-why')
    // Tap the first linked term → the glossary opens scrolled to that exact entry.
    const link = within(why).getByTestId(`glossary-link-${target!.term}`)
    fireEvent.click(link)
    expect(screen.getByTestId('glossary-modal')).toBeTruthy()
    expect(
      screen.getByTestId('glossary-modal').querySelector(`[data-term-id="${target!.term}"]`),
    ).toBeTruthy()
  })
})
